const imagesloaded = require('imagesloaded')
const Modernizr = require('modernizr')
const videojs = require('video.js')

require('css/site.css')
require('js/site/cookies_eu.js')
require('js/site/instafeed.min.js')
require('js/plugins/toastr.min.js')
require('js/site/jpreloader.js')
require('js/site/jquery.mousewheel.min.js')
require('js/bootstrap.min.js')
require('js/site/jquery.easing-1.3.pack.js')
require('jquery.stellar/jquery.stellar.js')
require('js/site/owl.carousel.min.js')
require('js/site/jquery.carouFredSel-6.2.1-packed.js')
require('js/site/tweetie.min.js')
require('js/site/jquery.sticky.js')
require('js/site/jplayer/jplayer.js')
require('js/site/jplayer/jplayer.playlist.js')
require('js/site/jquery.vegas.min.js')
require('js/site/css3-animate-it.js')
require('js/site/jquery.fractionslider.min.js')
require('js/site/jquery.mCustomScrollbar.min.js')
require('js/site/jquery.waitforimages.js')
require('js/site/bigvideo.js')
require('js/site/main.js')